version: 2
updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - 'dependencies'
      - 'github_actions'
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - 'dependencies'
      - 'npm'
