on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: Test Coveralls

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 14.x
        uses: actions/setup-node@v4.0.0
        with:
          node-version: 14.x

      - name: npm install, make test-coverage
        run: |
          npm install
          npm run build
          npm t -- --coverage

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
